Second Request
nextcode007/PyXMLParse pull request #2
Opened 2017-08-03 19:11 UTC by MasterofJS

2017-08-04 19:11 UTC, daronstinnett commented on render.py
> +    result = "TRANSUNION CREDIT REPORT\n\n"
how does this produce a line that is 77 characters?

2017-08-04 19:14 UTC, daronstinnett commented on render.py
> +    result += "<FOR>           <SUB NAME>          <MKT SUB>  <INFILE>    <DATE>     <TIME> \n"
do not put linebreaks in list items. `all(len(l) == 77 for l in result)` should always be True

2017-08-04 19:15 UTC, daronstinnett commented on render.py
> +    result += "***RECOVERY MODEL 1.0 SCORE +675 : ***" + "\n"
The static text in this section would mislead a person looking at this report. It should be removed if the data is not available in the xml.

2017-08-04 19:21 UTC, daronstinnett requested changes

2017-08-04 19:21 UTC, daronstinnett commented on render.py
> +    result += "T R A D E S" + "\n"
The public records and collections sections are missing
![image](https://user-images.githubusercontent.com/3218054/28983588-5f745dda-790f-11e7-9565-763bb3e4d65f.png)

2017-08-11 16:38 UTC, MasterofJS commented
When to show or hide Model Profile?
What is the tag for that?

2017-08-11 16:55 UTC, closed without merging